3. Sur machine, appliquer l’algorithme FP-Growth aux données de ce TD.
Indices :
- L’algorithme FP-growth est inclus dans la librairie mlxtend
- Le pré-traitement nécessaire pour les données, avant de les donner à l’algorithme FP-Growth, est
de les mettre sous la forme de booléens en colonnes (entre autres, la méthode
TransactionEncoder de mlxtend.preprocessing fait cela)

References:
- https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/fpgrowth/
- https://medium.com/@gabrielreversi/association-rules-the-fp-growth-algorithm-baaaa1263fea

# Exercice 1

| Transaction | Items   |
|-------------|---------|
| T₁          | A, B, C |
| T₂          | A, B, D |
| T₃          | A, B, E |
| T₄          | C, D, E |
| T₅          | C, D, E |

In [32]:
dataset = [
  ['A', 'B', 'C'],
  ['A', 'B', 'D'],
  ['A', 'B', 'E'],
  ['C', 'D', 'E'],
  ['C', 'D', 'E']
]

In [33]:
# preprocess transaction data using TransactionEncoder of mlxtend.preprocessing
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
te_ary

array([[ True,  True,  True, False, False],
       [ True,  True, False,  True, False],
       [ True,  True, False, False,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True]])

In [34]:
te_ary.astype(int)

array([[1, 1, 1, 0, 0],
       [1, 1, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1]])

In [35]:
te.columns_

['A', 'B', 'C', 'D', 'E']

In [36]:
te.get_feature_names_out()  # numpy.array of strings (objects).

array(['A', 'B', 'C', 'D', 'E'], dtype=object)

In [37]:
from mlxtend.frequent_patterns import fpgrowth
import pandas as pd

dataset = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets= fpgrowth(dataset, min_support=0.4, use_colnames=True)

In [38]:
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets, metric='confidence', min_threshold=1)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"frozenset({D, E})",frozenset({C}),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
1,"frozenset({D, C})",frozenset({E}),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
2,"frozenset({E, C})",frozenset({D}),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
3,frozenset({A}),frozenset({B}),0.6,0.6,0.6,1.0,1.666667,1.0,0.24,inf,1.000000,1.000000,1.0,1.000000
4,frozenset({B}),frozenset({A}),0.6,0.6,0.6,1.0,1.666667,1.0,0.24,inf,1.000000,1.000000,1.0,1.000000

# Exercice 2

| Transaction | Items   |
|-------------|---------|
| T₁          | A, E    |
| T₂          | A, D    |
| T₃          | A, B, E |
| T₄          | C, D, E |
| T₅          | C, D, E |

In [39]:
dataset = [
  ['A','E'],
  ['A','D'],
  ['A','B','E'],
  ['C','D','E'],
  ['C','D','E']
]

In [40]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
te_ary

array([[ True, False, False, False,  True],
       [ True, False, False,  True, False],
       [ True,  True, False, False,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True]])

In [41]:
from mlxtend.frequent_patterns import fpgrowth
import pandas as pd

dataset = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets= fpgrowth(dataset, min_support=0.4, 
use_colnames=True)

In [42]:
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets, metric='confidence', min_threshold=1)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({C}),frozenset({D}),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
1,frozenset({C}),frozenset({E}),0.4,0.8,0.4,1.0,1.250000,1.0,0.08,inf,0.333333,0.500000,1.0,0.750000
2,"frozenset({D, E})",frozenset({C}),0.4,0.4,0.4,1.0,2.500000,1.0,0.24,inf,1.000000,1.000000,1.0,1.000000
3,"frozenset({D, C})",frozenset({E}),0.4,0.8,0.4,1.0,1.250000,1.0,0.08,inf,0.333333,0.500000,1.0,0.750000
4,"frozenset({E, C})",frozenset({D}),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
5,frozenset({C}),"frozenset({D, E})",0.4,0.4,0.4,1.0,2.500000,1.0,0.24,inf,1.000000,1.000000,1.0,1.000000